#
# Copyright (c) 2017 Vinnie Falco (vinnie dot falco at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Official repository: https://github.com/boostorg/buffers
#

sudo: false

language: cpp

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test
    packages: &base_packages
      - python-software-properties
      - libffi-dev
      - libstdc++6
      - binutils-gold
      # Provides a backtrace if the unittests crash
      - gdb

matrix:
  include:
    # GCC 6.0, Debug + Coverage
    - os: linux
      compiler: g++-6
      env:
        - VARIANT=coverage
        - TOOLSET=gcc
        - COMPILER=g++-6
        - CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-6
            - lcov
            - *base_packages
          sources:
            - *base_sources

    # GCC 5.0, Valgrind
    - os: linux
      compiler: g++-5
      env:
        - VARIANT=valgrind
        - TOOLSET=gcc
        - COMPILER=g++-5
        - CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-5
            - valgrind
            - *base_packages
          sources:
            - *base_sources

    # Clang 3.8, UBasan
    - os: linux
      compiler: clang++-3.8
      env:
        - VARIANT=ubasan
        - TOOLSET=clang
        - COMPILER=clang++-3.8
        - CXXSTD=c++11
        - UBSAN_OPTIONS='print_stacktrace=1'
        - PATH=$PWD/llvm-$LLVM_VERSION/bin:$PATH
      addons:
        apt:
          packages:
            - clang-3.8
            - libssl-dev
            - *base_packages
          sources:
            - llvm-toolchain-precise-3.8
            - *base_sources

    # GCC 4.8, Release
    - os: linux
      compiler: g++-4.8
      env:
        - VARIANT=release
        - TOOLSET=gcc
        - COMPILER=g++-4.8
        - CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-4.8
            - *base_packages
          sources:
            - *base_sources

    # OSX Clang, C++14, Debug
    - os: osx
      compiler: clang++
      env:
        - VARIANT=debug
        - TOOLSET=clang
        - COMPILER=clang++
        - CXXSTD=c++14

    # OSX

before_install: &base_before_install
  - pip install --user https://github.com/codecov/codecov-python/archive/master.zip

install:
  - export LIB_NAME=buffers
  - export BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - export BOOST_ROOT="`pwd`"
  - export PATH="`pwd`":$PATH
  - git submodule update --init tools/build
  - git submodule update --init tools/boostdep
  - git submodule update --init libs/array
  - git submodule update --init libs/assert
  - git submodule update --init libs/config
  - git submodule update --init libs/core
  - git submodule update --init libs/exception
  - git submodule update --init libs/static_assert
  - git submodule update --init libs/throw_exception
  - git submodule update --init libs/type_traits
  - rm -rf libs/$LIB_NAME
  - mkdir libs/$LIB_NAME
  - cp -r $TRAVIS_BUILD_DIR/* libs/$LIB_NAME
  - ./bootstrap.sh

script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - cd ../boost-root
  - travis_retry libs/$LIB_NAME/tools/build-and-test.sh

after_script:
  - cat nohup.out || echo "nohup.out already deleted"

notifications:
  email:
    false
